"""init migration

Revision ID: 6c89f6d733be
Revises: 48788dc33a1f
Create Date: 2025-10-06 12:20:18.108717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c89f6d733be'
down_revision: Union[str, None] = '48788dc33a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'file_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
